### department 등록
POST http://localhost:8080/departments
Content-Type: application/json
X-USER-ID:nhnacademy

{
  "id":"CS0001",
  "name":"고객서비스1팀"
}

### department 조회
GET http://localhost:8080/departments/CS0001
X-USER-ID:nhnacademy

### department 수정
PUT http://localhost:8080/departments/CS0001
Content-Type: application/json
X-USER-ID:nhnacademy

{
  "name" : "CS1팀"
}

### department 삭제
DELETE http://localhost:8080/departments/CS0001
X-USER-ID:nhnacademy

### 부서 아이디 중복 체크
POST http://localhost:8080/departments
Content-Type: application/json
X-USER-ID:nhnacademy

{
  "id" : "L1001",
  "name" : "고객서비스1팀"
}

### 부서 not found
GET http://localhost:8080/departments/CS0002
X-USER-ID:nhnacademy

### L1001,A9003 부서조회
GET http://localhost:8080/department-members?departmentIds=L1001,A9003
Accept:application/json
X-USER-ID:nhnacademy

### 부서 아이디 파라미터 없음
GET http://localhost:8080/department-members
Accept:application/json
X-USER-ID:nhnacademy

### 파라미터 비어있음
GET http://localhost:8080/department-members?departmentIds=
Accept:application/json
X-USER-ID:nhnacademy

### Accept csv 예외
GET http://localhost:8080/department-members?departmentIds=L1001
Accept:application/csv
X-USER-ID:nhnacademy

### x-user-id : marco
GET http://localhost:8080/department-members?departmentIds=L1001
Accept:application/json
X-USER-ID:marco

### X-USER-ID : Empty
GET http://localhost:8080/department-members?departmentIds=L1001
Accept:application/json
X-USER-ID:

### X-USER-ID : NULL
GET http://localhost:8080/department-members?departmentIds=L1001
Accept:application/json

